### PR TITLE
Announcing community service award

### PR DESCRIPTION
**Pull request by gvwilson**
Approved by Steering Committee on 2016-09-08

### CODE REVIEW

**Comment by jduckles** [comment]
Why are we using confidential@software-carpentry.org for this. This places a burden on that person to process the submissions. This is not what they signed up to process confidential@ for. Using email also makes it very hard to be anonymous if that is the goal.

Having a form for nominations would keep it out of email and thereby more anonymous. @gvwilson can you just make a Google Form that asks "Who would you like to nominate?" and "Why would you like to nominate them?" and link to that instead?

**Comment by gvwilson** [comment]
Sure - what address should notifications about submissions be sent to?

**Comment by jduckles** [comment]
I've created nominations@software-carpentry.org, so please use it. It comes to me for now.

**Comment by gvwilson** [comment]
Updated - doesn't seem to need a form, but I can create one if required.

**Pull request merged**
