### PR TITLE
Add myself as an instructor

### PR DESCRIPTION
**Pull request by jesford**
I recently completed the Software Carpentry Instructor Training, and am adding myself to the website.

_Note: I'm not confident that I figured out all of the correct files that I'm supposed to add to the website repo, so let me know if I missed anything. Thanks!_

### CODE REVIEW

**Comment by jduckles** [comment]
@jesford Thanks for your PR.

Two things: 
1. add yourself to: `_data/includes.yml` as well, and 
2. please shrink your photo to be 120px wide.

**Comment by gvwilson** [comment]
`_data/includes.yml` can be regenerated by running `make includes` in 
the root directory.

**Comment by jesford** [comment]
Cool, thanks for the tips! Should be good to go now.

**Comment by jduckles** [comment]
Thanks @jesford!

**Pull request merged**
