### PR TITLE
new touch icons and removed tree icon from mobile view

### PR DESCRIPTION
**Pull request by todrobbins**
this addresses #30 and #65

### CODE REVIEW

**Comment by gvwilson** [comment]
Instead of removing all the icon files for various sizes of device, can you please replace them with appropriately-sized icons? `files/logo-source.svg` has the source in vector form. Everything else in this change looks good.

**Comment by todrobbins** [comment]
I'm on it! 🏃

**Comment by todrobbins** [comment]
@gvwilson I think we're good to go on the new favicon/touch icons. Firefox loads the icon as well.

**Comment by gvwilson** [comment]
Thanks @todrobbins - @pbanaszkiewicz and/or @jiffyclub can you please review?

**Comment by pbanaszkiewicz** [comment]
@gvwilson @todrobbins 

According to https://github.com/audreyr/favicon-cheat-sheet#basics we still need `favicon.ico` in the main root directory.

**Comment by todrobbins** [comment]
Doh! Will do.

**Comment by todrobbins** [comment]
@pbanaszkiewicz: Done!

**Comment by pbanaszkiewicz** [comment]
@todrobbins great!

@gvwilson I cannot spot anything wrong with the PR, but merge with caution - I have no iPhone / Windows Phone to test the favicons. Cheers!

**Comment by todrobbins** [comment]
I just added the dev site to my home screen on iOS (iPhone) and the icon looks great. So that's a relief. 😜

**Pull request merged**
