### PR TITLE
Blog post about spreadsheets and experimental models

### PR DESCRIPTION
**Pull request by gvwilson**

### CODE REVIEW

**Comment by jennybc** [comment]
Responding to your email ... I think it's a great post and basically agree with you.

I have all sorts of _opinions_ about why spreadsheets will be more buggy, even if you could equalize for mastery or whatever. But they are certainly untested.

Example: in R or Python, you refer to a set of numbers via a variable. And then you compute on that object holistically. Maybe take its mean or something? Most people, in Excel, refer to a set of numbers via a range like A5:A17 which they've selected via mouse. And perhaps let go too early? And left the last cell off by mistake? So there's a physical act involved versus a mental act, which I think is more error-prone. Of course the remedy is to use named ranges. Which few people do (and still usually involves a physical selection, but just once). Which comes back to your question of "equal mastery".

Example: in R or Python, there's a notion of a script. You can get the logic in front of your eyeballs. But in Excel, your eyeballs just see numbers and lots of them. To determine which cells are the result of formulas, most people must click around and watch the formula bar. Of course again, there are rather sophisticated ways to show all the formulas in Excel and even to highlight which cells depend on others. But few know or use them. Which comes back to the question of "equal mastery".

This issue on my sanesheets rant also brings up an interesting hypothesis about competing mental models: https://github.com/jennybc/sanesheets/issues/2.

Have you ever engaged Felienne Hermanns on this? I don't know anyone else who studies this stuff so carefully. Maybe she knows or will get inspired by your post!

**Comment by Felienne** [comment]
Hi Greg,

Great post, and you know I agree with most that you write.

One angle "in favor of" spreadsheets I think you are missing is the liveness and direct feedback model. So in concreto I think I disagree with

 "Yes, it's hard to write unit tests for spreadsheets"

It is very simple! You write "if(A1<>5, "ERROR", "OK") And this is something people actually do (8% of spreadsheets exhibited this behaviour in a study we did) Or you use conditional formatting, or input validation. There are features in Excel that help. And also, looking over your data to see if it makes sense in easy, as you can see everything. 

For me, this seems a lot harder in Python/R, there is no easy data view or even data validation without lots of programming.

And obviously your point that "the fact that they _could_ is irrelevant" still stands. 

Thanks for this. Will retweet when it is out there ;)

**Comment by gvwilson** [comment]
Thanks very much for the feedback, Felienne - I've poached your example :-)

**Comment by gvwilson** [comment]
Thanks for the feedback - I agree that all of these are reasons why 
spreadsheets would be more error-prone, but I'd be happy knowing _that_ 
rather than knowing _why_ at this point if it helped us figure out how 
we're going to measure or rank these things in general.

**Pull request merged**
