### PR TITLE
Draft of Summary for SWC Bug BBQ

### PR DESCRIPTION
**Pull request by ttimbers**
@BillMills @gvwilson @k8hertweck @rgaiacs please review this draft of a summary blog post for what happened at the SWC Bug BBQ. Apologies this took so long for me to write...

### CODE REVIEW

**Comment by k8hertweck** [comment]
This is great! Thanks for taking the time to summarize.

**Comment by rgaiacs** [comment]
@ttimbers Thanks very much for the post. It is great. +1 to merge.

**Comment by ttimbers** [comment]
@rgaiacs the image I embedded using .md formatting doesn't show up in the html blog post... should I use html to embed it instead?

**Comment by ttimbers** [comment]
@BillMills - do you know why the image shows up in `.md` using `alt tag` but fails to show up on the `.html` version of the page? Do I need to use the HTML `` tag to make this work? The blog post is really lacking without your graph...

**Comment by gvwilson** [comment]
Fixed in 91542de21684

**Pull request merged**
