### PR TITLE
Explaining our requirements for supporting translations of lessons

### PR DESCRIPTION
**Pull request by gvwilson**
@k8hertweck and @tracykteal can you please review? And @tracykteal if this looks good I'll copy over to the DC site.

### CODE REVIEW

**Comment by k8hertweck** [comment]
This works for me. I'm glad to have a place to send folks who ask about translations. Thanks!

**Comment by jduckles** [comment]
@gvwilson It has the UCSF job post associated with the commit. You may want to remove that, but otherwise it looks good.

**Comment by gvwilson** [comment]
I don't know why that's happening - nothing shows up in the desktop diff 
between gh-pages and this branch for the UCSF job ad.  I'll merge as-is 
then blast my repo.

**Comment by gvwilson** [comment]
Thanks @k8hertweck.

**Pull request merged**
