### PR TITLE
MarkerClusterer cloned

### LINKED ISSUE #387: No pins on map
Chrome:

screenshot from 2016-05-16 19-17-02

Firefox:

screenshot from 2016-05-16 19-17-43

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
This fixes #387.

In order to do that I decided to clone MarkerClusterer locally so that we have a fixed version of it and shouldn't worry about it not working.

### CODE REVIEW

**Comment by gvwilson** [comment]
So what was the root cause of the breakage? A change in MarkerCluster? Or...?

**Comment by pbanaszkiewicz** [comment]
They stopped hosting it on code.google.com (switched to GitHub) so we started having 404 errors.

**Comment by gvwilson** [comment]
Gotcha. :+1: to merge.

**Comment by jduckles** [comment]
Thanks @pbanaszkiewicz!

**Pull request merged**
