### PR TITLE
Fee clarification

### PR DESCRIPTION
**Pull request by katieannemills**
Clarification of fees charged for SWC workshops. Not to be merged before approval from the SC. Change summary:
- clearly bullet three fee schedules to distinguish between them
- clarify that waivers are not required for self-organized workshops
- clarify that travel and accommodation costs are the host's responsibility beyond SCF fees
- do not commit to any administrative support for self-organized workshops

### CODE REVIEW

**Comment by jduckles** [comment]
Thanks @BillMills.  

@maneesha, any comments here before I merge?

**Comment by maneesha** [comment]
I'm actually confused by this line:

> ...for $2500 USD if you are not a Software Carpentry Foundation partner, and $1250 USD if you are.

I don't think our existing partner agreements say this - they just say they are paying the agreed amount in lieu of workshop fees.  And since we're about to roll out the bronze/silver/gold tiered system we should probably say something like "$2500 if you are not a SCF partner.  Partner organizations receive discounted fees.  Read more [here](url)."

+10000000000000 for making it clear we won't provide _any_ admin support for self organized workshops.

**Comment by katieannemills** [comment]
@maneesha the $1250 number is cut-and-pasted from what is on the website now - but I agree with your substitution - should I change that, @jduckles? Also per your comment, I just added a phrase to make it _extra_ clear that we won't provide admin support for self-org workshops.

@jduckles, there's actually an SC motion open to merge this on Friday - does that seem like overkill? I can go either way.

**Comment by katieannemills** [comment]
Alright, this passed the SC today, and I removed the out-of-date $1250 discount for partners. Good to merge - we'll add in the link to the bronze-plat table once that's live.

**Pull request merged**
