### PR TITLE
Create 2016-05-23-first-dc-r-darwin.md

### PR DESCRIPTION
**Pull request by orchid00**
Hi, it is the first time I'm writing to the posts on the Software Carpentry Site so I hope this is the right way to go. 
I have written a post about the first data carpentry workshop in Darwin Australia. If you have comments let me know. I added two pictures saved somewhere else but I think they should be accessible to everyone. Couldn't find the best way to centre the first collage image, if anyone has tips, I welcome those. 

Thanks,

### CODE REVIEW

**Comment by weaverbel** [comment]
@orchid00 I don't think you need to sign your name at the bottom of the post as you are identified in the blog header.

**Comment by orchid00** [comment]
thanks Belinda, If it is standard then I will delete it.
I just had some comments on this _right now_ from COMBINE fellow, I just need to go out for a meeting, will update when I'm back. So I think this can wait a bit until it gets published.

**Comment by weaverbel** [comment]
@orchid00 If you are making changes, then I would delete the pull request for now or it might get merged. Also I usually merge it into my fork and then do the pull request from there so it ends up if the right place - i.e. in the right posts folder. But maybe you don't need to do that.

**Comment by orchid00** [comment]
I made some fixing, it is ready from my side

**Pull request merged**
