### PR TITLE
Online workshops

### PR DESCRIPTION
**Pull request by maneesha**
Make the workshop list on the Software Carpentry site use the same format as on The Carpentries site.  This includes the "**" to note Mix and Match workshops, and to use the globe icon for online workshops.

The SWC website had the workshop tables hard coded in to each page they appear on.  This PR gets as far as creating a `workshop_table` template in `_includes` and using that template on the index page, the (upcoming) workshops page, and the past workshops page.

The data feeds that the SWC site uses are designed so that the `tag` field is the lesson program initials (SWC) only, and doesn't include the other tags like online, circuits, etc.  This means that even if the code that generates the table works, there is no data to show.

@fmichonneau  which of the following would be a better way to resolve this? 
1. Fixing each lesson program's data feed to include all tags
2. Passing all_workshops feed to each lesson program site, and filtering by lesson program when the table is generated.
3. Passing all_workshops feed to each lesson program site, and filtering when the site is built (in update_fields.sh)

### CODE REVIEW

**Comment by maneesha** [comment]
Once we figure this out I will work on the same thing for the  DC and LC websites.

**Review by fmichonneau — APPROVED** [review]
I've looked at this quickly but it seems good to me!

**Comment by maneesha** [comment]
Thanks @fmichonneau There is still the question about how to fix the workshop feeds so they include all tags. I included a few suggestions above. What would be your recommendation?

**Comment by fmichonneau** [comment]
Ha sorry about this @maneesha, I don't know how I missed that!

I think option 2 is the best for now. It'd make things easier to only have to curate one data feed for each of past and upcoming workshops instead of having to worry about the lesson programs.

I pushed an additional commit that takes care of doing this for SWC (as I wanted to see what it would like) and also deletes some older files that were left in the `_data` folder. Let me know what you think but if this looks good to you, then you could implement the same for the other lesson program websites and we can delete the lesson program-specific data feeds.

**Comment by maneesha** [comment]
Thanks @fmichonneau 
I just added in one more fix to remove the lesson program checks from the workshops table, since that filtering is happening when the table gets built.  This also makes the "**" for Circuits display properly.   Merging now.

**Pull request merged**
