### PR TITLE
Bi-lingual post on Carpentry for Latin America init

### PR DESCRIPTION
**Pull request by weaverbel**

### CODE REVIEW

**Comment by weaverbel** [comment]
No rush for this given the recent flurry of new posts - it can wait till Monday.

**Comment by maneesha** [comment]
I think it would be good to acknowledge the tragedies (earthquake, hurricane) faced in these regions and that it may impact their involvement in the near future.

**Comment by weaverbel** [comment]
@orchid00 can you please address Maneesha's point above and then I will merge? I can copy whatever you put in to the version on the DC site.

**Comment by tracykteal** [comment]
@weaverbel touched base with @orchid00 and she'd like to post as is. Merging.

**Pull request merged**
