### PR TITLE
Adding draft Python Gapminder lesson so people can find it

### PR DESCRIPTION
**Pull request by weaverbel**
Not sure who to credit as author though - Greg has most commits of anyone so I chose him ! There were 16 authors!

### CODE REVIEW

**Comment by ErinBecker** [comment]
@weaverbel Greg gets "most commits" because he pulled in the template. :-)

The author should be  whoever has the second most commits.

**Comment by weaverbel** [comment]
Thanks @ErinBecker Next up is @rgaiacs - Raniere, who has done the most work to create this lesson? There are 16 authors in AUTHORS.md and we can't list them all.

**Comment by ErinBecker** [comment]
Agreed with @gvwilson that we should like the maintainer here. Sorry I hadn't looked at where you were trying to credit authorship. For the DC Ecology lessons, we have an "Authors" tag at the beginning of each lesson that lists the original/major authors for each episode, but for the website we list maintainers.

**Comment by k8hertweck** [comment]
The maintainer of this lesson is currently @ntmoore (although we're looking for another to assist if anyone has any ideas!). The plan I've discussed previously with Nathan and the other maintainers is that we'll eventually retire Python inflammation and replace with Gapminder. Nathan, would it be ok with you if this lesson is listed as contributed for now, to make it easier for folks to find?

**Comment by ntmoore** [comment]
Yes, listing it as contributed seems like a good idea to me

**Comment by weaverbel** [comment]
OK, change made to list @ntmoore as the maintainer so I think the PR can be merged now. I get asked a lot about how to find this lesson which is why I want it listed.

**Comment by rgaiacs** [comment]
Looks good to me.

**Pull request merged**
