### PR TITLE
Adding African Task force info as blog and static page

### PR DESCRIPTION
**Pull request by anelda**

### CODE REVIEW

**Review by weaverbel — COMMENTED** [review]
I think there is a typo in the filename which is causing issues when I try to work with this file: pages/sucom_africa.html

Should be subcom?

**Review by weaverbel — COMMENTED** [review]
Ignore last comment ! Just saw you fixed it.

**Comment by anelda** [comment]
The task force html page refuses to build though. Do you know why?

**Comment by weaverbel** [comment]
I will sort it out in my morning B

**Comment by weaverbel** [comment]
OK, we have some issues here. I am disentangling stuff bit by bit. @anelda I have created the post separately and it has merged. I have updated the subcom page myself with the new data and it has merged. I tried creating the african_tf page and that failed so I have deleted that to stop it bringing down the website and I will now start again.

Please close this whole PR now and I will get the info on in my own way. I have got the data from the african_tf file locally and am trying to work out why it fails to build. We don't want any of this to merge now as I have created the files myself.

**Pull request closed without merging**
