### PR TITLE
Create 2016-04-24-subcommittes-taskforces.md

### PR DESCRIPTION
**Pull request by raynamharris**
New blog to be posted. Twitter announcements can go out as soon as the blog goes live.

### CODE REVIEW

**Comment by jduckles** [comment]
@raynamharris thanks for this. The links are broken, I'm going to merge and then fix them before the website build takes place. Thanks to all who worked on pulling this together!

**Comment by raynamharris** [comment]
Thanks @jduckles. I tried to fix them last night but its hard to see when its not live. 

Also, I just edited the authors... Can you merge again?

**Comment by jduckles** [comment]
I think I have your author's edits. All links are fixed now too.

**Comment by raynamharris** [comment]
@jduckles ah, sorry.  Not sure where the chages I thought I made 14 minutes ago went.. I had to submit a new PR to update.

**Pull request merged**
