### PR TITLE
WIP Move people bios and info to _data

### PR DESCRIPTION
**Pull request by andreabedini**
This is a work in progress for #39. The new system generates (roughly) the same html. I ran into some encoding issues that I had to fix. Perhaps it will be a good idea to ask people to check their info.

to do
- [ ] do projects
- [ ] add fields for roles or responsibilities

### CODE REVIEW

**Comment by gvwilson** [comment]
Thanks very much for this, Andrea - I'll merge it when you tell me it's 
ready, but for the moment I really want to focus on the stuff in the 
Version 1.0 milestone, since that's what's stopping us from switching 
over.  (We can use the current preprocessor method for gathering people 
and projects for another couple of weeks, but we can't ship if the 
GeoJSON maps aren't showing up or if the mouseovers aren't showing 
people's faces etc.)
Thanks,
Greg

**Comment by gvwilson** [comment]
OK, I think we're ready for this now...

**Comment by gvwilson** [comment]
Hi @andreabedini 
1.  How did you do the translation from _include files to _data files? awk script?
2.  How are you including these files in team.html and elsewhere? (We also use them in scf.html.)

**Comment by andreabedini** [comment]
hi @gvwilson,
1. I used pandoc to convert the html files into md, and then python to turn md into yaml, adding the id tag.
2. for team.html

``` diff
 <div class="row">
-  {% for person in site.data.includes.people %}
-    <div class="small-6 columns">{% include {{person}} %}</div>
+  {% for person_hash in site.data.people %}
+  {% assign person = person_hash[1] %}
+  <div class="small-6 columns">
+    <p id="{{person.id}}" data-toggle="tooltip" title="<img src='{{site.filesurl}}/people/{{person.id}}.jpg' alt='{{per
+      {{ person.biography | markdownify }}
+    </p>
+  </div>
     {% cycle '', '</div>' %}
     {% cycle '', '<div class="row">' %}
```

while for scf.html I did

``` diff
   <div class="small-4 columns">
     <h4>Executive Director</h4>
-    {% include people/duckles.jonah.html %}
+    {{ site.data.people['duckles_jonah'].content }}
   </div>
```

I tried to do the same for projects but the html is slightly more complex (there's the image tag that might or might not be there). I'll try again today using beatifulsoup to parse the html in python.

I tried to rebase the branch on current master but it fails at the moment.

EDIT: sorry but you guys are working too fast :)

**Comment by gvwilson** [comment]
If you can make this work, and include the conversion script, I'd be 
very happy to rebase it - thanks!

**Comment by pbanaszkiewicz** [comment]
Hi @andreabedini and @gvwilson,

is this work a website-part of #90 (and AMY's https://github.com/swcarpentry/amy/issues/603)? Or should I contribute my 2¢?

Cheers,
Piotr

**Comment by gvwilson** [comment]
Yup, they're all connected.

**Comment by gvwilson** [comment]
This one has fallen a long way out of date.

**Comment by andreabedini** [comment]
Sorry, life has been very busy :-(

Sent from my phone
Andrea

**Pull request closed without merging**
