### PR TITLE
Add blog post about Lesson Infrastructure Subcommittee

### PR DESCRIPTION
**Pull request by rgaiacs**

### CODE REVIEW

**Comment by k8hertweck** [comment]
Perhaps add link to the proposal for the subcommittee?

https://github.com/swcarpentry/board/issues/155

**Comment by wking** [comment]
> Perhaps add link to the proposal for the subcommittee?

[Already there][1]?

[1]: https://github.com/swcarpentry/website/pull/638/files#diff-081f44084f45aba567164ec0eb843414R16

**Comment by k8hertweck** [comment]
Awesome, thanks for pointing me towards it!

**Comment by rgaiacs** [comment]
@jduckles Can yo merge this on Monday? Thanks.

**Pull request merged**
