### PR TITLE
Autobuilder for weekly update

### PR DESCRIPTION
**Pull request by rgaiacs**

### CODE REVIEW

**Comment by gvwilson** [comment]
Doesn't `bin/get-dashboard.py` already collect some of this information?

**Comment by rgaiacs** [comment]
> Doesn't `bin/get-dashboard.py` already collect some of this information?

`bin/get-dashboard.py` collect the issues and pull request that are open. So far this collect contributions. @jduckles asked for this plus the list of most accessed pages and future workshops. I have to clean up the script for the most accessed pages and will talk with @pbanaszkiewicz about AMY.

**Comment by gvwilson** [comment]
I think maintenance would be easier if you added code to 
get-dashboard.py to get contributions (and that could be shown in the 
dashboard as well as the weekly update).

**Comment by gvwilson** [comment]
@rgaiacs any interest in pushing this further, or shall we wait for the Great Website Redesign?

**Comment by rgaiacs** [comment]
@gvwilson Do we still want this? If yes, could you close this one and open a new issue on the new repository?

**Comment by gvwilson** [comment]
Up to @jduckles

**Pull request closed without merging**
