### PR TITLE
Add draft of blog post with proposal to workshop template

### PR DESCRIPTION
**Pull request by rgaiacs**
This is related with https://github.com/swcarpentry/workshop-template/pull/459. I need to read it again before go live.

### CODE REVIEW

**Comment by weaverbel** [comment]
Would you like me to review this @rgaiacs or have you got a lot of rework to do? Happy to give it a once-over.

**Comment by rgaiacs** [comment]
> Would you like me to review this

I will try to read it again today at the end of my day. Thanks.

**Comment by rgaiacs** [comment]
I'm happy with the text now. @weaverbel Can you have a look and merge?

**Comment by rgaiacs** [comment]
@weaverbel ff70df3 looks good to me.

**Pull request merged**
