### PR TITLE
added blog post on hpccarpentry

### PR DESCRIPTION
**Pull request by psteinb**
... as suggested [here](https://github.com/swcarpentry/hpc-novice/issues/24#issuecomment-299396469).

Would love to see feedback by @ChristinaLK, @shwina and @zonca as they are explicitly mentioned. Other feedback is also welcome!

Note, that the International Supercomputing Conference ([ISC17](www.isc-hpc.org)) is taking place in Frankfurt/Main, Germany. If accepted, it would be a nice match to put this blog out until Wednesday, June 21, 2017.

### CODE REVIEW

**Comment by jduckles** [comment]
@psteinb I've set the time a bit into the future so that recent blog posts don't all show up at once. Thank you for writing this up!

**Comment by psteinb** [comment]
that's totally fine with me. I am happy I could contribute and hope it's meaningful.

**Comment by ChristinaLK** [comment]
I think this looks great.

**Comment by zonca** [comment]
very interesting, thanks for sharing this!

**Pull request merged**
