### PR TITLE
Update tags for blogs

### PR DESCRIPTION
**Pull request by techieeliot**

### CODE REVIEW

**Comment by techieeliot** [comment]
Happy Hacktoberfest!

**Review by serahkiburu — CHANGES_REQUESTED** [review]
Hi @techieeliot, thank you so much for the PR! Let's remove the `Software Carpentry` tags as all posts in this blog fall under the category. Using the [list of tags](https://carpentries.org/posts-by-tags) on the central Carpentries blog as a cheatsheet might also help.

**Comment by serahkiburu** [comment]
for #1086

**Comment by techieeliot** [comment]
Referencing the "Selecting Tags for your Carpentries Blog", noting the section ["By Carpentry"](https://docs.carpentries.org/topic_folders/communications/guides/select-blog-tags.html#by-carpentry) and the "original source" tags. Please advise.

**Comment by techieeliot** [comment]
That should have fixed the changes on that set. Please review.

**Comment by serahkiburu** [comment]
Thanks @techieeliot, I took a short break, but back at my desk now, and will merge this, and your other PRs shortly. Thank you for making our Tagathon such a fruitful one 🙌

**Pull request merged**
