### PR TITLE
Fixing refs to instructor training

### PR DESCRIPTION
**Pull request by gvwilson**

### CODE REVIEW

**Comment by jduckles** [comment]
@gvwilson This has the NCSA blog post rolled in which I already merged I think.

**Comment by gvwilson** [comment]
?? I only see one changed file `pages/join.html`.

**Comment by jduckles** [comment]
d67381f shows up in #488 too, in fact with the same SHA.

**Comment by gvwilson** [comment]
No idea - want me to re-bake, or can we merge as-is? Doesn't show any conflicts.

**Pull request merged**
