### PR TITLE
Short notice about the PLoS Git paper

### PR DESCRIPTION
**Pull request by gvwilson**
@jdblischak please check

### CODE REVIEW

**Comment by jdblischak** [comment]
Looks good. Thanks!

**Comment by gvwilson** [comment]
Thanks @jdblischak - over to @jduckles to merge.

**Comment by wking** [comment]
I'd recommend linking to [1](https://www.authorea.com/users/5990/articles/17489), because the typography is much nicer
than it is in PLoS.  I'll attach some screenshots for comparison, but
after slogging through the tiny spaces, injected newlines, etc. in the
PLoS paper it was frustrating to find “Methods” linking to something
that looked a lot better.

**Comment by wking** [comment]
PLoS rendered with evince v3.14.2, and those same sections in Authorea rendered with Firefox 38.1.1:

PLoS doesn't mark `git init` as verbatim:

plos-git-init

But Authorea does:

authorea-git-init

PLoS has odd intents (and font-size changes?) for some verbatim sections:

plos-odd-indents

But Authorea is consistent:

authorea-odd-indents

PLoS injects empty lines in some verbatim sections and uses a font that does not emphasize space characters:

plos-injected-newlines

But Authorea does not inject empty lines and does use a monospaced font:

authorea-injected-newlines

PLoS wraps some lines where it shouldn't, dedenting _beyond_ the leading ± in a diff:

plos-narrow-wrapping

Authorea does wrap for narrow browsers, but never beyond the leading ±.  And with a sufficiently-wide browser it doesn't wrap at all:

authorea-narrow-wrapping

**Comment by jdblischak** [comment]
Good point, @wking. I was definitely frustrated that our hard work to nicely format the document on Authorea is less evident in the final version PLOS version. I don't understand why the double-spacing with non-monospaced text is their default for displaying code.

As a solution, what if we updated the blog post to additionally mention that we wrote the article with Authorea, and also suggest that it would be easier to read the code in the that version?

**Comment by wking** [comment]
On Fri, Jan 22, 2016 at 09:59:05AM -0800, John Blischak wrote:

> As a solution, what if we updated the blog post to additionally
> mention that we wrote the article with Authorea, and also suggest
> that it would be easier to read the code in the that version?

That sounds good to me, and gives you a chance to plug a Git/LaTeX
workflow.  I think that's a plus even if the end renderer is not open
source.

**Pull request merged**
