### PR TITLE
Tagging blog posts

### PR DESCRIPTION
**Pull request by tobyhodges**
Re: #1086 

I set aside an hour and added tags to posts without any, then rather abitrarily chose years/posts to work on. Hope this is helpful.

### CODE REVIEW

**Comment by serahkiburu** [comment]
many thanks Toby, and congratulations on your first contribution on this specific repo 🎉

**Review by serahkiburu — CHANGES_REQUESTED** [review]
Hi @tobyhodges, I've given the tags you suggested a once-over. 
If time allows, please use[ this handbook page](https://docs.carpentries.org/topic_folders/communications/guides/select-blog-tags.html) as a guide to edit the suggestions you've put in, and [this list of standardised tags on the central carpentries blog](https://carpentries.org/posts-by-tags/) as a cheatsheet for tags you can suggest.

**Comment by tobyhodges** [comment]
Thanks Serah - it's been a busy few days. I'll try to get to this tomorrow.

**Comment by serahkiburu** [comment]
Awesome, thanks Toby 🙌

**Comment by maneesha** [comment]
@kmomar @acrall We have a number of issues about tags on blog post that have been open for up to two years. Do you want to keep these open? 

For this, there were suggestions Serah had made and then this just sat.  I'm OK merging or closing as you see fit.

**Comment by kmomar** [comment]
@maneesha @acrall We will merge this post, but do you know what the conflict is in this that needs to be resolved?

**Comment by maneesha** [comment]
I've fixed the merge conflicts and merged.

**Pull request merged**
