### PR TITLE
Add new instructors

### PR DESCRIPTION
**Pull request by maneesha**

### CODE REVIEW

**Comment by gvwilson** [comment]
Thanks - did we get a pic as well?

**Comment by maneesha** [comment]
No pic.  Should I remove the img tag?

**Comment by gvwilson** [comment]
Please leave as-is for now (the Javascript mouseover code will be 
unhappy without the img tag, because I'm sloppy).  Can you please ping 
her to see if she's comfortable adding a pic?
Thx,
G

**Comment by maneesha** [comment]
That's it for the instructor profile updates I've had in queue... ready to merge.

**Pull request merged**
