### PR TITLE
Create 2016-03-10-instructor-debriefing-round-04-05.md

### PR DESCRIPTION
**Pull request by raynamharris**
I didn't write a blog post after the February 23rd session, so I thought I would merge the two. 

Would @mckays630 or @ttimbers like to add anything from the Feb 23rd session?

Also, @weaverbel and @rgaiacs need to add comments form the March 8th session before posting. 

Thanks!

### CODE REVIEW

**Comment by ttimbers** [comment]
@raynamharris I don't think anyone showed up at my session that day, so nothing to add.

**Comment by jduckles** [comment]
Please let me know when you're ready to merge.

**Comment by raynamharris** [comment]
@jduckles still waiting for updates from the evening workshop from @rgaiacs and/or @weaverbel

**Comment by rgaiacs** [comment]
@jduckles and @raynamharris I will do it tomorrow (Sunday).

**Comment by weaverbel** [comment]
I'll do something tonight too - sorry for delay.

**Comment by weaverbel** [comment]
I was going to maybe add something but the etherpad has gone and I couldn't seem to get back to an earlier one. Not sure now what were the main points, apart from the issues with Windows and with downloading data.

**Comment by raynamharris** [comment]
@weaverbel Sorry, I deleted it too soon. But, that version had been archived here: http://pad.software-carpentry.org/swc-debriefing-evening/timeslider#13844

In case you didn't know, almost all of the ether pad archives have been saved. To view them, click the clock button at the stop then use the arrows to move forward or back in time.

**Comment by weaverbel** [comment]
Thanks @raynamharris Now I haven't done this before so if I do want to add something, do I just fork your contribution and make my changes there? I won't be able to do it tonight though - it would have to be some time tomorrow. If you really need to get it merged, then don't wait for me.

**Comment by raynamharris** [comment]
No worries @weaverbel. You should be able to add your contribution to the proposed new file without forking, but you can fork if that feels more comfortable. No rush on making your contribution.

**Comment by rgaiacs** [comment]
@raynamharris I sent a [pull request](https://github.com/raynamharris/website/pull/1/files) to you that will update this one. Do you have permission to merge this?

**Comment by rgaiacs** [comment]
> Now I haven't done this before so if I do want to add something, do I just fork your contribution and make my changes there?

@weaverbel I was planning to attend the help session on 16 March at 23:00 UTC but no attendees signed up so if you want I can help you with the pull request to this one.

**Comment by raynamharris** [comment]
@rgaiacs I do not have permission to merge.

**Comment by jduckles** [comment]
@raynamharris Is this ready to go? I can merge if so.

**Comment by weaverbel** [comment]
@raynamharris @rgaiacs I did want to add a couple of things but they aren't desperate - I am more interested in learning how to do it so I know how to proceed for next time. I can't edit this file - permissions issue  so should I just fork it and make my changes? Sorry to be a dummy.

**Comment by raynamharris** [comment]
No worries @weaverbel. I am also just figuring this out. Feel free to fork and edit.

**Comment by weaverbel** [comment]
Hi @raynamharris I've now done a PR to update your version https://github.com/raynamharris/website/pull/2 and we should be good to go once you've merged.

**Comment by raynamharris** [comment]
Now this is ready to go @jduckles 

Thanks everyone for comments!

**Pull request merged**
