### PR TITLE
Blog post announcing election to revise SC election procedures

### PR DESCRIPTION
**Pull request by k8hertweck**
There are two things I'd like to add to this blog post still (waiting on final word from @JasonJWilliamsNY and @gvwilson):
1. Specify who is in charge of the ballot
2. Describe who a member should contact if they do not receive a ballot

### CODE REVIEW

**Comment by k8hertweck** [comment]
This is ready to post following approval from the Steering Committee.

**Comment by k8hertweck** [comment]
Should we include a statement about membership for folks who may not have taught, but contributed in other ways? The list was updated strictly based on teaching, and I want to be sure we're allowing inclusivity for involvement in other ways (which our membership clearly includes).

**Comment by maneesha** [comment]
@k8hertweck Good point. I added a line about other contributions for membership.

**Comment by jduckles** [comment]
Ready to go?

**Comment by k8hertweck** [comment]
More than half of the SC has approved, so I'll say yes, good to go.

**Pull request merged**
