### PR TITLE
New blog entry

### PR DESCRIPTION
**Pull request by pevans-gfz**
Here is some commentary about the pair of workshops held in Potsdam in May. Sorry, no photo(s), though maybe we can find one. I'll ask around.

### CODE REVIEW

**Review by weaverbel — CHANGES_REQUESTED** [review]
Hi Peter - great post. I just have one suggestion - that instead of having the links at the end, as you do, that you include them inline as you have done for the lesson links and so on.  I could do that for you but I think it's good to go through the process for yourself so you know next time how to do it all. 

Thanks Belinda

**Comment by pevans-gfz** [comment]
Okay, I've done that, and added a photo.

**Review by weaverbel — CHANGES_REQUESTED** [review]
Hi again. Sorry for delay in merging but I am not sure the image has been correctly formatted in markdown to render properly. Have a look here: https://raw.githubusercontent.com/swcarpentry/website/gh-pages/_posts/2017/06/2017-06-19-mqu-ttt.md for examples of how images should be formatted in markdown.

**Comment by pevans-gfz** [comment]
... and I think I've fixed that for you now.

**Comment by weaverbel** [comment]
Ok, thanks so much for persevering @pevans-gfz I don't have merge rights on this repository so I can't publish it but I hope it will be merged tomorrow.

**Comment by jduckles** [comment]
Thanks for your contribution Peter (@pevans-gfz)! It's great to see the community growing in Germany!

**Pull request merged**
