### PR TITLE
Fixing mentorship page

### PR DESCRIPTION
**Pull request by gvwilson**
@tracykteal reported this page 404'ing. I believe the problem is line breaks in the quoted string in the YAML header. This version puts everything on one line, and renders properly for me on my desktop. @BillMills @ChristinaLK can you please check?

### CODE REVIEW

**Comment by ChristinaLK** [comment]
I'm trying to build locally + check, but am getting thousands of liquid template errors - is there a way to suppress those, or do I just have to wait for it to finish?

**Comment by ChristinaLK** [comment]
NVM, it worked.  Yes, looks good.  Before you merge, can you fix the etherpad link in line 7 (towards the beginning?)  That's my fault from the original PR - I didn't add the http: prefix so the link isn't working.  :P

**Comment by gvwilson** [comment]
What errors are you getting?  (I don't get any.)  And what version of 
Jekyll are you using?

**Comment by gvwilson** [comment]
Etherpad fix pushed - I use `site.pad_url` to pull in the URL from the 
configuration.

**Comment by tracykteal** [comment]
@ChristinaLK I just upgraded to Jekyll 3.2.1 and am also getting all those errors now.

**Comment by gvwilson** [comment]
I'm using 3.1.2, which I believe is what the server is using as well.  
Please paste the error messages so I can start debugging.

**Comment by ChristinaLK** [comment]
When I run `make serve`, I get this over and over (I assume for all the posts in the posts directory?):

```
 Liquid Warning: Liquid syntax error (line 7): Expected end_of_string but found id in "{{ page.title escape_once }}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 9): Unexpected character & in "page.image.caption_url && page.image.caption" in /_layouts/post.html
```

It eventually finishes and serves the website, so it's not like anything is broken-broken.

**Comment by ChristinaLK** [comment]
I also have jekyll 3.2.1 (which is acting weirdly with bundler? sass? ugh ruby gems).  But I don't think that's the issue here.

**Comment by gvwilson** [comment]
This looks like a bug in the original template - it should be 
"page.title | escape_once" (with a pipe character).  I see four uses of 
escape_once (_layouts/post.html, _layouts/page.html, 
_layouts/page-fullwidth.html, and blog/archive.html).  Can you please 
try inserting a pipe character in all four and re-running with your 
version of Jekyll?

**Comment by ChristinaLK** [comment]
Did that.  Now have: 

```
 Liquid Warning: Liquid syntax error (line 9): Unexpected character & in "page.image.caption_url && page.image.caption" in /_layouts/post.html
 Liquid Warning: Liquid syntax error (line 5): Unexpected character & in "page.image.caption_url && page.image.caption" in /_layouts/page-fullwidth.html
```

(many times for each).  Also:

```
Liquid Warning: Liquid syntax error (line 138): Unexpected character / in "{{site/filesurl}}" in pages/scf_history.html
```

and

```
Liquid Warning: Liquid syntax error (line 101): [:dot, "."] is not a valid expression in "postIndex in (currentPostIndex...lastPostIndex)" in blog/dates.html
```

**Comment by gvwilson** [comment]
sorry, dunno what else to try...

**Comment by ChristinaLK** [comment]
I mean, it works, it just spits out a couple hundred of line of gobbledygook as part of the process.

**Pull request merged**
