### PR TITLE
Making lessons page more attractive.

### LINKED ISSUE #67: Have site and reference before repo on lessons page
The table with the different lessens on http://dev.software-carpentry.org/lessons/ has the columns with links in the order repo-site-reference-maintainers. I suspect many visitors will be most interested in the site, not so much the repo. Perhaps change the order of the links to site-reference-repo-maintainers?

### PR DESCRIPTION
**Pull request by gvwilson**
1.  Column headers for lesson tables.
2.  Icons instead of words for links.
3.  Slideshows in columns instead of just rows.

Closes #67.

### CODE REVIEW

**Comment by lexnederbragt** [comment]
Apologies, although I managed to build the lessons.html page locally, it doesn't show the icons. Could you provide a screenshot? So much for the github PR model...

**Comment by gvwilson** [comment]
Are you running 'make serve' and then looking at 
http://0.0.0.0:4000/lessons/, or trying to view it statically?

**Comment by lexnederbragt** [comment]
Oh, of course (perhaps a little how-to in the README or in a CONTRIBUTING file would help for others?). Now I look at he the http://0.0.0.0:4000/lessons/ one. It looks great! Can you center the icons? They are left-aligned now.

**Comment by gvwilson** [comment]
Apparently I can't: I've used `td align="center">...</td>` around the icons, and they still show up left-justified. If I merge this PR, can you please file a separate issue suggesting that the icons be centered, and we'll get someone to work on that?

**Pull request merged**
