### PR TITLE
Blog post summarizing general considerations for RFC responses

### PR DESCRIPTION
**Pull request by k8hertweck**
Wait to merge until an OK from @kcranston or @ethanwhite (ok to add one/both of you as authors? cross posting to DC blog?)

### CODE REVIEW

**Comment by ethanwhite** [comment]
Looks really good.

> As the size of the community increases, however, we are attempting to strike a balance between representing community input while ensuring we meet business obligations.

I would probably cut this sentence. It sets up business and community as in conflict. I don't think that is the case here and while part of the justification for the appointed board is to provide stability in the business and staff side of things it is also to facilitate broader community engagement by involving people who would not have become part of the board otherwise.

I also think it's worth emphasizing that we've looked outside of SWC and DC in thinking about how to set up governance by revising:

> Specific decisions about governance have built on previous experiences from both organizations while attempting to uphold other priorities described above. 

to

> Specific decisions about governance have been based on previous experiences from both organizations,  successful leadership models in other large volunteer projects, and the priorities described above.

**Comment by kcranston** [comment]
Looks good! I agree with Ethan's two points. Yesterday, we also discussed adding some text about conflict with SWC bylaws being unavoidable as we merge. Should we add that?

**Comment by jduckles** [comment]
@tracykteal or @weaverbel can you please cross post then merge?

**Comment by k8hertweck** [comment]
I made the changes @ethanwhite suggested and tried to include a sentence describing how we are aware of the SWC rules and are adapting them in the context of the merger. @kcranston, I also added you as an author to represent the joint SWC/DC drafting of the post; hope that's ok!

**Comment by ethanwhite** [comment]
I forgot about your author question. I'm happy to be included if that's useful, but there is no need to. I personally like the symmetry of having one member of the merger committee from each org as the authors.

**Comment by weaverbel** [comment]
is this post ready to merge?

**Comment by kcranston** [comment]
+1 from me, but I don't have merge permissions on this repo

**Comment by k8hertweck** [comment]
Yes, good to merge, @weaverbel !

**Comment by hlapp** [comment]
Great post, @k8hertweck. I'm impressed with the tone and balance of this writeup.

**Pull request merged**
