### PR TITLE
fix svg files

### PR DESCRIPTION
**Pull request by fmichonneau**

### CODE REVIEW

**Comment by jduckles** [comment]
Just curious what did this "fix"?

**Comment by rgaiacs** [comment]
> Just curious what did this "fix"?

From my understand, I didn't fix anything for the website because the logos didn't have the issue being discuss at https://github.com/swcarpentry/lesson-example/issues/171. From my understanding, @fmichonneau applied the same script to all SVG.

**Comment by jduckles** [comment]
@rgaiacs Ah great, thanks for that background.

**Comment by rgaiacs** [comment]
Firefox 58.0.2

Left: Pull request
Right: 34b0d39 from https://github.com/swcarpentry/styles/

screenshot from 2018-02-19 16-16-12

**Pull request merged**
