### PR TITLE
Making new website URL-compatible with old.

### LINKED ISSUE #79: Add .htaccess file to redirect old URLs to new
The site needs a .htaccess file to redirect old URLS (such as /pages/team.html) to the new ones (such as /team/). We can't deploy until we have this.

### PR DESCRIPTION
**Pull request by gvwilson**
1.  Adding `htaccess` (which becomes `.htaccess`) with lots of rewrite rules.
2.  Modifying `pages/scf.html` (which becomes `/scf/`) to link to other documents so that they're not duplicated.

The rewrite rules need careful testing.

This will close #79.

### CODE REVIEW

**Comment by djacquel** [comment]
.htaccess didn's work on github pages.
For redirecting, you can have a look at [jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from) which works on Github pages.

**Comment by gvwilson** [comment]
If jekyll-redirect-from is a plugin, we shouldn't use it - we want this 
site to run on GitHub gh-pages.

**Comment by andreabedini** [comment]
jekyll-redirect-from is bundled with the github-pages gem, see #76.

**Comment by gvwilson** [comment]
Nice - I'll close my PR and submit a new one using 
jekyll-redirect-from.  Thanks both.

**Comment by gvwilson** [comment]
Closed in favor of #83.

**Pull request closed without merging**
